FROM postgres:13.0-alpine

COPY ./init.db.sh /usr/local/bin/init.db.sh
COPY ./custom-entrypoint.sh /usr/local/bin/custom-entrypoint.sh

RUN chmod +x /usr/local/bin/init.db.sh
RUN chmod +x /usr/local/bin/custom-entrypoint.sh

USER postgres

ENTRYPOINT ["/usr/local/bin/custom-entrypoint.sh"]