# Generated by Django 4.2.9 on 2024-09-07 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controller',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controller_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicebase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='devicebase',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='home',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homeuser',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeUser_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='homeuser',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeUser_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.citycoordinates'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uibase',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uibase',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
