# Generated by Django 4.2.9 on 2024-09-16 12:50

from django.db import migrations

from django.db import migrations

def add_iran_cities(apps, schema_editor):
    CityCoordinates = apps.get_model('dashboard', 'CityCoordinates')
    
    cities = [
        ('Tehran', '51.3890', '35.6892'),
        ('Mashhad', '59.6167', '36.2972'),
        ('Isfahan', '51.6776', '32.6539'),
        ('Karaj', '50.9923', '35.8327'),
        ('Shiraz', '52.5319', '29.5926'),
        ('Tabriz', '46.2919', '38.0800'),
        ('Qom', '50.8764', '34.6401'),
        ('Ahvaz', '48.6842', '31.3183'),
        ('Kermanshah', '47.0650', '34.3277'),
        ('Urmia', '45.0686', '37.5550'),
        ('Rasht', '49.5832', '37.2809'),
        ('Zahedan', '60.8629', '29.4963'),
        ('Hamadan', '48.5146', '34.7983'),
        ('Kerman', '57.0788', '30.2839'),
        ('Yazd', '54.3675', '31.8974'),
        ('Ardabil', '48.2933', '38.2498'),
        ('Bandar Abbas', '56.2808', '27.1832'),
        ('Arak', '49.6892', '34.0954'),
        ('Eslamshahr', '51.2359', '35.5641'),
        ('Zanjan', '48.4787', '36.6736'),
        ('Sanandaj', '46.9926', '35.3219'),
        ('Qazvin', '50.0041', '36.2636'),
        ('Khorramabad', '48.3557', '33.4871'),
        ('Gorgan', '54.4398', '36.8427'),
        ('Sari', '53.0601', '36.5659'),
        ('Kashan', '51.4340', '33.9850'),
        ('Semnan', '53.3919', '35.5769'),
        ('Shahrekord', '50.8549', '32.3256'),
        ('Birjand', '59.2213', '32.8649'),
        ('Ilam', '46.4227', '33.6374'),
        ('Bojnord', '57.3331', '37.4753'),
        ('Yasuj', '51.5880', '30.6682'),
    ]

    for city, longitude, latitude in cities:
        CityCoordinates.objects.create(
            city_name=city,
            longitude=longitude,
            latitude=latitude
        )

def remove_iran_cities(apps, schema_editor):
    CityCoordinates = apps.get_model('dashboard', 'CityCoordinates')
    CityCoordinates.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_controller_created_by_and_more'),
    ]

    operations = [
        migrations.RunPython(add_iran_cities, remove_iran_cities),
    ]