# Generated by Django 4.2.9 on 2024-09-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_add_iran_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='curtainui',
            name='animation_duration',
            field=models.IntegerField(default=5000),
        ),
    ]
