# Generated by Django 4.2.9 on 2024-09-23 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_advance_thumbnail.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_curtainui_animation_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='dashboard_users_avatar/original_files/')),
                ('avatar_thumbnail', django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to='dashboard_users_avatar/thumbnail_files/')),
                ('telegramID', models.CharField(default='', max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboardUser', related_query_name='dashboardUser', to='auth.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboardUser', related_query_name='dashboardUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
