# Generated by Django 4.2.9 on 2024-09-23 20:43

from django.db import migrations, models
import django_advance_thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_homeuser_avatar_thumbnail_dashboarduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboarduser',
            name='telegramID',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
