# Generated by Django 4.2.9 on 2024-10-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_homeuser_avatar_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerDevice',
            fields=[
                ('devicebase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dashboard.devicebase')),
            ],
            bases=('dashboard.devicebase',),
        ),
    ]
