# Generated by Django 4.2.9 on 2024-10-20 21:32

from django.db import migrations, models
import django.db.models.deletion
import django_advance_thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_controllerdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIElementBackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='ui_elements_background_images/')),
                ('background_image_thumbnail', django_advance_thumbnail.fields.AdvanceThumbnailField(blank=True, null=True, upload_to='ui_elements_background_images/thumbnail_files/')),
                ('style_options', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='uibase',
            name='tablet_mode_background_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.uielementbackgroundimage'),
            preserve_default=False,
        ),
    ]
