# Generated by Django 4.2.9 on 2024-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_uielementbackgroundimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicebase',
            name='modbus_channel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
