# Generated by Django 4.2.9 on 2024-10-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_devicebase_modbus_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='uart_data_bits',
            field=models.CharField(choices=[('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='7', max_length=50),
        ),
        migrations.AddField(
            model_name='controller',
            name='uart_flow_control',
            field=models.CharField(choices=[('None', 'None'), ('RTS/CTS', 'RTS/CTS'), ('Xon/Xoff', 'Xon/Xoff')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='controller',
            name='uart_parity',
            field=models.CharField(choices=[('None', 'None'), ('Odd', 'Odd'), ('Even', 'Even')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='controller',
            name='uart_stop_bits',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=50),
        ),
    ]
