# Generated by Django 4.2.9 on 2024-10-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_datapointfunction_io_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapointfunction',
            name='read_data_model',
            field=models.CharField(choices=[('discrete_input', 'Discrete input'), ('coil', 'coil'), ('input_register', 'Input register'), ('holding_register', 'Holding register')], default='input_register', max_length=30),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='read_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='read_start_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='write_data_model',
            field=models.CharField(choices=[('discrete_input', 'Discrete input'), ('coil', 'coil'), ('input_register', 'Input register'), ('holding_register', 'Holding register')], default='holding_register', max_length=30),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='write_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='write_start_address',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
