# Generated by Django 4.2.9 on 2024-10-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_datapointfunction_read_data_model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datapointfunction',
            old_name='write_data_model',
            new_name='modbus_write_data_model',
        ),
        migrations.RenameField(
            model_name='datapointfunction',
            old_name='read_quantity',
            new_name='modbus_write_quantity',
        ),
        migrations.RenameField(
            model_name='datapointfunction',
            old_name='read_start_address',
            new_name='modbus_write_start_address',
        ),
        migrations.RemoveField(
            model_name='datapointfunction',
            name='read_data_model',
        ),
        migrations.RemoveField(
            model_name='datapointfunction',
            name='write_quantity',
        ),
        migrations.RemoveField(
            model_name='datapointfunction',
            name='write_start_address',
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='internal_buffer_read_data_model',
            field=models.CharField(choices=[('1b', '1 Bit'), ('4b', '4 bit'), ('8b', '8 bit'), ('16b', '16 bit'), ('32b', '32 bit'), ('64b', '64 bit')], default='1b', max_length=30),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='internal_buffer_read_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='internal_buffer_read_start_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='internal_buffer_write_data_model',
            field=models.CharField(choices=[('1b', '1 Bit'), ('4b', '4 bit'), ('8b', '8 bit'), ('16b', '16 bit'), ('32b', '32 bit'), ('64b', '64 bit')], default='1b', max_length=30),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='internal_buffer_write_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='internal_buffer_write_start_address',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='modbus_read_data_model',
            field=models.CharField(choices=[('discrete_input', 'Discrete input'), ('coil', 'coil'), ('input_register', 'Input register'), ('holding_register', 'Holding register')], default='input_register', max_length=30),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='modbus_read_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapointfunction',
            name='modbus_read_start_address',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
