# Generated by Django 4.2.9 on 2024-10-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_write_data_model_datapointfunction_modbus_write_data_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='uart_baud_rate',
            field=models.CharField(choices=[('75', '75'), ('300', '300'), ('1200', '1200'), ('2400', '2400'), ('4800', '4800'), ('9600', '9600'), ('14400', '14400'), ('19200', '19200'), ('28800', '28800'), ('38400', '38400'), ('57600', '57600'), ('115200', '115200')], default='9600', max_length=50),
        ),
    ]
