# Generated by Django 4.2.9 on 2024-09-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkagerule',
            name='parent_zone',
        ),
    ]
