# Generated by Django 4.2.9 on 2024-09-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_linkagerule_parent_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkagerule',
            name='status',
            field=models.CharField(choices=[('enable', 'enable'), ('disable', 'disable')], default='enable', max_length=50),
        ),
    ]
