# Generated by Django 4.2.9 on 2024-09-07 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web_app', '0003_alter_linkagerule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkagerule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_rules_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='linkagerule',
            name='last_edited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linkage_rules_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
