# Generated by Django 5.0.7 on 2024-07-26 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicebase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='devicebase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='devicebase',
            name='descriptions',
        ),
        migrations.RemoveField(
            model_name='devicebase',
            name='last_edited_by',
        ),
        migrations.RemoveField(
            model_name='devicebase',
            name='last_modified',
        ),
    ]
